# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

setup_travis

default_platform(:ios)

before_all do
  xcversion(version: "11.1")
end

def version_number
  if ENV["TRAVIS_BRANCH"].match?(/^release\/.*$/)
    return ENV["TRAVIS_BRANCH"].split("/").last
  else
    return get_version_number
  end
end

platform :ios do
  desc 'Runs the unit tests in QCardsTests'
  lane :unit_test do
    scan(scheme: "QCardsTests")
  end

  desc 'Runs the UI tests in QCardsUITests'
  lane :ui_test do
    scan(scheme: "QCardsUITests")
  end

  desc "Installs the certificates and profiles locally"
  private_lane :certificates do |options|
    UI.user_error!('No keychain name provided') if options[:temporary_keychain_name].nil?
    tmp_keychain = options[:temporary_keychain_name]

    create_keychain(
      name: tmp_keychain,
      password: tmp_keychain,
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true
    )

    match(
      type: "appstore",
      keychain_name: tmp_keychain,
      keychain_password: tmp_keychain,
      readonly: true
    )

    sh "security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k #{tmp_keychain} #{tmp_keychain}"
  end

  desc 'Deploys QCards to App Store'
  lane :deploy_to_app_store do
    tmp_keychain = "temporary_keychain"
    certificates(temporary_keychain_name: tmp_keychain)

    increment_version_number(version_number: version_number)
    increment_build_number

    gym(
      scheme: "QCards",
      verbose: true,
      clean: true
    )

    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )

    delete_keychain(
      name: tmp_keychain
    )
  end
end
