# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

setup_travis

default_platform(:ios)

before_all do
  xcversion(version: "11.1")
end

platform :ios do
  desc 'Runs the unit tests in QCardsTests'
  lane :unit_test do
    scan(scheme: "QCardsTests")
  end

  desc 'Runs the UI tests in QCardsUITests'
  lane :ui_test do
    scan(scheme: "QCardsUITests")
  end

  desc 'Deploys QCards to App Store'
  lane :deploy_to_app_store do
    keychain_name = ENV["KEYCHAIN_NAME"]
    keychain_password = ENV["KEYCHAIN_PASSWORD"]

    create_keychain(
      name: keychain_name,
      password: keychain_password,
      default_keychain: true,
      timeout: 3600,
      unlock: true,
      add_to_search_list: true
    )

    match(
      keychain_name: keychain_name,
      keychain_password: keychain_password,
      readonly: true,
      verbose: true
    )
    
    increment_build_number(
      build_number: latest_testflight_build_number() + 1
    )

    build_app(scheme: "QCards")

    deliver(
      submit_for_review: true,
      reject_if_possible: true,
      skip_screenshots: true,
      skip_metadata: true,
      force: true
    )

    delete_keychain(
      name: keychain_name
    )
  end
end
